import type { Metadata } from 'next'
import { Manrope } from 'next/font/google'
import { Cabin } from 'next/font/google'
import cn from 'classnames'
import './globals.css'
import { Providers } from './providers'

const fontHeading = Manrope({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-heading',
})

const fontBody = Cabin({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-body',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn('antialiased', fontHeading.variable, fontBody.variable)}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
